package com.app.model;


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class AutoGeneratedId {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    public AutoGeneratedId() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


}
