package com.app.model;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "users")
public class User extends AutoGeneratedId {
    @Column(unique = true)
    private String login;
    @Column
    private String password;
    @OneToMany(mappedBy = "owner", cascade = CascadeType.PERSIST)
    private List<Apartment> apartmentsList;

    public User(String login, String password) {
        apartmentsList = new ArrayList<Apartment>();
        this.login = login;
        this.password = password;
    }

    public void addApartmentToList(Apartment apartment){
        apartmentsList.add(apartment);
    }

    public User() {
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Apartment> getApartmentsList() {
        return apartmentsList;
    }

    public void setApartmentsList(List<Apartment> apartmentsList) {
        this.apartmentsList = apartmentsList;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + getId() +
                ", login='" + login + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
